|                                           |
|-------------------------------------------|
| Title: A Gentle Introduction to scRNA-seq |
| Author: poloarol                          |
| Date: November, 2022                      |

# A. Single-Cell RNA-Seq vs Bulk RNA-Seq

## a. Bulk RNA-Seq

      - Estimate average expression level for each gene across a population of cells
      - Characterize expression signatures between two groups or conditions
      - Find and annotate new genes, gene isoforms, and other transcripts

## b. Single-Cell RNA-Seq

      - Allows for comparison of the transcriptomes of individual cells
      - Assess transcriptional similarities and differences within a population of cells
      - Identify rare cell populations
      - Trace lineages and developmental relationships between heterogeneous cell states

## 1. Basic Terminologies

### a. Unique Molecular Identifiers (UMI):

      - Molecular tags that can be applied to detect and quantify the unique transcripts
      

### b. Features:

      - Gene names

### c. Barcodes:

      - Single-cell sequencing experiments use short DNA barcode "tags" to identify reads from the same cell

### d. Count Matrix or Feature-Barcode Matrix or Gene-Barcode Matrix:

      - A matrix of counts representing the number of unique observations of each feature within eac cell barcode

### e. Doublets:

      - When two cells are encapsulated into one reaction volume

## B. Packages for single-cell RNA-Seq Analysis

### a. R

      - SingleCellExperiment
      - Seurat
      - monocle3
      - Scater

### b. Python

      - ScanPy
      - SquidPy
      - SCVI-tools

## 3 Seurat Object

### a. assays

      - A list of assays for this project

### b. meta.data

      - Contains meta-information about each cell, starting with number of features detected (nFeature) and the original identity class (orig.ident); more information is added using AddMetaData

### c. active.assay

      - Name of the active, or default, assay; settable using DefaultAssay

### d. active.ident

      - The active cluster identity for this Seurat object; settable using Idents

### e. graphs

      - A list of Graph objects

### d. neighbors

      - ...

### e. reductions

      - A list of dimensional reduction objects for this object

### f. images

      - A list of spatial image objects

### g. project.name

      - Name of the project

### h. misc

      - A list of miscellaneous information

### i. version

      - Version of Seurat this object was built under

### j. commands

      - A list of logged commands run on this Seurat object tools
    A list of miscellaneous data generated by other tools, should be filled by developers only using Tool<-
