------------------------------------------------------------------------

Title: understading Bioinformatics file formats Author: poloarol Date: Nov. 2022

------------------------------------------------------------------------

# 1. FASTA and FastQ

## a. FASTA

    - Represent nucleotide and amino acid sequences of nucleic acids and protein
    - A sequence n this format begins with a single-line description (">"), followed by lines of
      sequence data
    - A FASTA file can conntain multiple sequences
    - File extensions: .fasta, .fa, .fna (FASTA nucleic acid), .faa (FASTA amino acid)
    - Text files
    - Contains reference genomes

## b. FastQ

    - Each entry is associated with 4 lines:
      a. Line 1 begins with a @ character is followed by seqeunce identifier
      b. Line 2 is the raw sequence letter
      c. Line 3 begins with a + character and is optionally followed by the same sequence identifier again
      d. Line 4 are quality scores (PHRED) for the sequence in Line 2

    - The files are generated by the sequencers
    - They can be read as input to aligners (BWA), QCtools (FastQC) and assemblers (SPAdes)
    - File extensions: .fastq, .fq

#### Quality = PHRED Scores

    -   A quality score for each base pair.
    -   It indicates how confident we can be that the base was correctly identified
    -   Q = -10log10(p), where p is the base call is incorrect

# 2. SAM vs BAM

    -   SAM: Sequence Alignment Map
    -   BAM: Binary Alignment Map. Compressed representation of SAM
    -   Store data produced by next generation sequencers
    -   SAM files are stored in Tab-delimited formats:

      a.  HEADER
        - Program, Reference sequence, Read Group
        
      b.  ALIGNMENT
      - QNAME
      - FLAG
      - RNAME
      - POS
      - MAPQ
      - CIGAR
      - RNEXT
      - PNEXT
      - TLEN
      - SEQ
      - QUAL
      - Optional metadata
      
#### a. Simplified Sequence to Variant Workflow
    - Raw data -> FASTQ
    - FASTQ -> BWA -> SAM
    - SAM -> SAM tools -> BAM
    - BAM -> BCF tools -> VCF
    

# 3. GFF3 and GTF
    - Eukaryotic genes possess both Exons and Intron, with untranslate regions
    - Promoter regions are uptream, to initiate transcription

#### a. General Feature Format  and Gene Transfer Format (GTF)
    - tsv-based format
    - Annonate genomic intervals
    - Have 9 fields that describe the gene
    - Features are hierarchical
    
#### b. Use cases
    - Visualize genomic features
    - Mapping & Quantifying RNA_Seq reads
    - Any tool that requires location of genomic features


# 3. VCF and gVCF

#### a. What is a variant Calling Format (VCF) file?
    - Output of bioinformatics pipeline
    - Stores read variations
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    